# Jaseel's Fab Academy 2016
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jaseel's Fab Academy
email: Jaseel@fellow.startupmission.in
description: This is Jaseel's Fab Academy 2016 documentation website.
baseurl: "/jas"  # the subpath of your site
url: "http://archive.fabacademy.org"
twitter_username: jaseelmjp1
github_username:  jaseel1
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
